### PR TITLE
Add test for graceful stack upgrades

### PR DESCRIPTION
**Pull request by sophiewigmore**
## Summary

Part of #651, add integration test that ensures graceful stack upgrades are successful.

Per discussion on issue, no changes were needed to the Go language family buildpacks to enable graceful stack upgrades. However, a test has been added solely to ensure that this behaviour is not broken in the future, either by a new version of Go, or changes to the buildpack logic.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by fg-j — COMMENTED** [review]
I've just pushed up a commit that tweaks a couple things
- checks the Stack ID, not the Builder Name when deciding whether to run upgrade tests. this is more accurate to the spirit of the test
- tweaks the cgo server so it doesn't log that the DB is closed while the server is still running
- pushes the stack upgrade test into the main test suite; this way it'll be run in parallel with the other tests instead of sequentially after the others finish

@sophiewigmore let me know what you think about those changes; i'll approve if we are on the same page

**Comment by sophiewigmore** [comment]
- stack ID check makes sense!
- Thank you for fixing the app, those log lines were some leftovers I forgot about while messing around with the exploration work
- running in parallel makes sense to me
Thanks frankie!

**Comment by fg-j** [comment]
@sophiewigmore re: the stack ID check, I hadn't considered that my change would make the tests run on tiny and base. good point. I'd be satisfied with a check that says "if the stack is bionic base, run the upgrade tests". That way, users bringing their own bionic base builder can still run the tests.

This means we *won't* test upgrading from an arbitrary stack to the jammy stack. I think that's reasonable, because we're only guaranteeing Ubuntu Bionic --> Ubuntu Jammy graceful upgrades at the moment.

I'll put in a commit momentarily.

**Review by fg-j — APPROVED** [review]

**Comment by sophiewigmore** [comment]
Thank you!!

**Pull request merged**
