### PR TITLE
RFC: Offload all source removal onto a buildpack

### PR DESCRIPTION
**Pull request by ForestEckhardt**
[Readable](https://github.com/paketo-buildpacks/go/blob/source-removal/rfcs/0002-source-removal.md)

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
I will make a change to the RFC itself but the source-removal buildpack it now full featured

**Comment by ryanmoran** [comment]
I've made a couple of additions. This looks fine to me, contingent upon the `source-removal` buildpack moving into a place that is maintained by the org, like `paketo-community` and a resolution of the `buildpack.yml` vs. Build Plan RFC.

**Comment by ForestEckhardt** [comment]
Converting to draft because I am not currently actively working on this.

**Comment by ForestEckhardt** [comment]
Closing this RFC as we are going to resolve this issue directly in `go-build`. We may refactor it out if `source-removal` is pulled into Paketo.

**Pull request closed without merging**
