### PR TITLE
add license field

### PR DESCRIPTION
**Pull request by AccraZed**
## Summary

This addition is with reference to #385, to add licensing information to the buildpack.toml file. I used [this BP commit](https://github.com/paketo-buildpacks/sbt/commit/c439455eba617aee80d165ea928b0ef1d88b1e63) as reference. I have PRs ready for all the other implementation BPs for Go, so if this looks alright I can PR everything else too.
## Use Cases

As the issue states, this would allow users to see licensing information through their app image's BoM.
## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ryanmoran** [comment]
@kvedurmu do you know how we would verify that this is actually working? I can't figure out where I would see this license information in any output.

**Comment by kvedurmu** [comment]
@ryanmoran I think we ultimately want this to be surfaced in the BOM, but at the moment I don't think it would show up anywhere in the output. My original intent of this issue is that the License field is listed as "unknown" if you go to the Buildpacks registry. So, after a release is cut with this change we should see the license listed on https://registry.buildpacks.io/buildpacks/paketo-buildpacks/go

**Comment by ryanmoran** [comment]
I played around with this a bit and it appears that `jam` is dropping this metadata when it packages up the buildpack. I've opened [this PR](https://github.com/paketo-buildpacks/packit/pull/193) to make sure we keep these new fields when we package the buildpack up.

**Comment by fg-j** [comment]
A [version of jam has been released](https://github.com/paketo-buildpacks/packit/releases/tag/v0.13.0) that now supports the licenses field. Are there any other blockers on this PR @ryanmoran?

**Comment by fg-j** [comment]
@ryanmoran are there any further blockers on this PR (or the analogous ones across the go implementation repos?)

**Comment by ryanmoran** [comment]
> @ryanmoran are there any further blockers on this PR (or the analogous ones across the go implementation repos?)

I don't think so, but I haven't yet pulled this branch with the new version of `jam` to test it out.

**Comment by fg-j** [comment]
After rebasing the PR so it's using jam v0.13.0, I can confirm that the `buildpack.toml` that's packaged into the `buildpack.tgz` includes: 
```toml
[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go"
  id = "paketo-buildpacks/go"
  name = "Paketo Go Buildpack"
  version = "9.9.9"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go/blob/main/LICENSE"

```

**Review by fg-j — APPROVED** [review]

**Pull request merged**
