### PR TITLE
Restructure the Go buildpack ecosystem

### PR DESCRIPTION
**Pull request by ForestEckhardt**
[Readable](https://github.com/paketo-buildpacks/go/blob/restructure-go/rfcs/0000-restructure-go.md)

### CODE REVIEW

**Comment by ryanmoran** [comment]
@ForestEckhardt this largely looks good to me. I've landed another commit that changes the names of the buildpacks to align a bit more closely with their purpose and changes the descriptions to be a bit pithier.

**Comment by ForestEckhardt** [comment]
@ryanmoran The changes look perfectly fine to me! I would be happy to start working on this whenever you approve and merge.

**Comment by ryanmoran** [comment]
@ForestEckhardt I've added a third order group where neither go mod, nor dep are used. This would be the case where I'm just using standard library code, maybe a simple hello world app. I think this makes it clearer that `go-build` is the next thing that should be worked on.

I think we have the following steps to get this structure:
- [ ] Add a language-family test suite
- [ ] Rename `go-compiler` to `go-dist`
- [ ] Create `go-build`
- [ ] Rename `go-mod` to `go-mod-vendor`
- [ ] Pull `go build` code out of `go-mod-vendor` and replace with `go-build` in the order group
- [ ] Pull `go build` code out of `dep` and replace with `go-build` in the order group
- [ ] Create new `dep-ensure` that runs `dep ensure`
- [ ] Pull `dep ensure` code out of `dep` and replace with `dep-ensure` in the order group

**Comment by ForestEckhardt** [comment]
@ryanmoran I think that the plan you have laid out makes total sense and I would love to start working on it as soon as it get merged!

**Pull request merged**
